;; prelude-shims.ss — the Gambit target's syntax/API shims, loaded FIRST in every
;; boot path (rt.ss owns the load; gambitcheck loads it directly).
;;
;; G1 (jolt-mj95.2): the syntax/API layer for native gsi (Gambit 4.9.7). Every
;; shim here exists because the curated host subset (the G2 boot manifest) uses
;; an R6RS/Chez spelling that Gambit does not provide under that name — see
;; .dirge/gambit-spike-findings.md for the probe verdicts this builds on, and
;; the census lists below for exactly what is shimmed (grep as data, not by eye).
;;
;; DESIGN NOTES
;; ------------
;; - Gambit's plain-script top level lacks several (gambit) module names
;;   (format/printf/system/...), so the prelude starts by importing the (gambit)
;;   module. Gambit's native define-record-type is renamed out of the way
;;   (%gambit-native-record, unused) because it is the define-type sugar with
;;   keyword syntax — NOT the R6RS form the host writes.
;; - Records: Gambit has NO record mechanism with parent support and inclusive
;;   predicates (the findings doc's "R7RS define-record-type works" verdict is
;;   wrong: the (scheme base) version IS Gambit's native macro, which rejects the
;;   R6RS field-spec form; probe 2026-08-07). The host needs both — the jrec
;;   family (records.ss define-jrec-family) generates parent clauses, and
;;   collections.ss dispatches on (jrec? x) as a GENERIC record test, which
;;   requires the base predicate to be true of child instances. So the shim
;;   implements define-record-type itself over native vectors: an instance is
;;   #(type-id field0 field1 ...) with parent fields laid out first, a load-time
;;   registry maps type-name -> rtd (id parent-name nfields field-names), and
;;   constructor/accessor/setter/predicate bindings are eval'd into the
;;   interaction environment (the same mechanism def-var! relies on — the G0
;;   pin that eval'd defines are visible to later evals).
;;   DIVERGENCE (documented): a gambit record IS a native vector, so (vector? r)
;;   is #t where Chez gives #f. Host dispatch never tests raw vector? on records
;;   (jolt-vector? = pvec?, and pvec is itself a record), so the jolt-level
;;   classification is unaffected. Accessor/predicate type checks use the same
;;   ancestor-chain logic as R6RS.
;; - nongenerative uids are accepted and IGNORED (no image capability on this
;;   target). protocol/parent in record clauses: parent IS supported (the jrec
;;   family needs it); protocol is an error.

;; Gambit's plain-script top level lacks several (gambit) module names
;; (format/printf/system/...), so the prelude imports the (gambit) module —
;; EXCEPT its native define-record-type (the define-type sugar with keyword
;; syntax, NOT the R6RS form the host writes), which this file replaces with
;; its own translator below.
(import (except (gambit) define-record-type let-values let*-values
                ;; EVERY (gambit) export the unit redefines at top level must
                ;; be excluded: gsi tolerates redefining an import, but under
                ;; gsc -target js the import binding and the local define
                ;; resolve independently and references read #!void at runtime
                ;; (keyword? in key-hash was the diagnosing case — values.ss
                ;; redefines it as jolt's keyword-t?). List generated by
                ;; intersecting gambit.sld's exports with the manifest's
                ;; top-level defines; regenerate when either changes.
                cond-expand current-time define-record-type error fl* fl+ fl- fl> floor fold-right fx* fx+ fx- fxand fxarithmetic-shift-left fxarithmetic-shift-right fxbit-count fxior fxmax fxmin fxmodulo fxnot fxquotient fxremainder fxxor fxzero? gensym getenv interaction-environment keyword? let*-values let-values read-file-string thread-yield!))

;; let-values/let*-values: bound in gsi's interpreter but compiled as VARIABLE
;; references by gsc -target js ((#!void #!void) at runtime — probed 4.9.7).
;; The standard syntax-rules definitions over call-with-values, ours on both
;; targets for consistency.
(define-syntax let-values
  (syntax-rules ()
    ((_ () body ...) (let () body ...))
    ((_ ((formals expr) rest ...) body ...)
     (call-with-values (lambda () expr)
       (lambda formals (let-values (rest ...) body ...))))))
(define-syntax let*-values
  (syntax-rules ()
    ((_ () body ...) (let () body ...))
    ((_ (binding rest ...) body ...)
     (let-values (binding) (let*-values (rest ...) body ...)))))

;; ============================================================================
;; interaction environment — the eval target for record bindings and, later,
;; def-var!. R7RS (scheme repl) interaction-environment if bound, else Gambit's
;; repl-environment. Either way (interaction-environment) returns THE top-level
;; environment where define lands (G0 pin).
;; ============================================================================

(define %jolt-interaction-environment
  (guard (e (#t (repl-environment)))
    (interaction-environment)))

(define (interaction-environment)
  %jolt-interaction-environment)

;; ============================================================================
;; R6RS define-record-type translator
;; ============================================================================

(define jolt-record-table (make-table test: eq?))     ;; type-name sym -> rtd
(define jolt-record-id-table (make-table test: eqv?)) ;; id fixnum -> rtd
(define jolt-record-counter 0)

;; rtd = #(id parent-name nfields field-name-list)
(define (jolt-record-id-of name)
  (let ((rtd (table-ref jolt-record-table name #f)))
    (and rtd (vector-ref rtd 0))))

(define (jolt-record-nfields id)
  (vector-ref (table-ref jolt-record-id-table id #f) 2))

(define (register-jolt-record-type! name parent-name fields)
  (let* ((parent-id (and parent-name (jolt-record-id-of parent-name)))
         (parent-n (if parent-id (jolt-record-nfields parent-id) 0))
         (n (+ parent-n (length fields)))
         (id (begin (set! jolt-record-counter (+ jolt-record-counter 1))
                    jolt-record-counter))
         (rtd (vector id parent-name n fields)))
    (table-set! jolt-record-table name rtd)
    (table-set! jolt-record-id-table id rtd)
    id))

;; Is ID a descendant-or-self of ANCESTOR-ID? Inclusive predicate semantics.
(define (jolt-record-ancestor? id ancestor-id)
  (or (= id ancestor-id)
      (let* ((rtd (table-ref jolt-record-id-table id #f))
             (pn (and rtd (vector-ref rtd 1))))
        (and pn (jolt-record-ancestor? (jolt-record-id-of pn) ancestor-id)))))

(define (make-jolt-record-ctor id n)
  (lambda args
    (if (not (= (length args) n))
        (error 'record-constructor "wrong number of arguments" n (length args))
        (let ((v (make-vector (+ n 1))))
          (vector-set! v 0 id)
          (let loop ((i 0) (args args))
            (if (< i n)
                (begin (vector-set! v (+ i 1) (car args))
                       (loop (+ i 1) (cdr args)))
                v))))))

(define (make-jolt-record-pred id)
  (lambda (x)
    (and (vector? x)
         (>= (vector-length x) 1)
         (fixnum? (vector-ref x 0))
         (jolt-record-ancestor? (vector-ref x 0) id))))

(define (make-jolt-record-field id parent-n own-index)
  (+ 1 parent-n own-index))

(define (make-jolt-record-accessor id parent-n own-index)
  (let ((off (make-jolt-record-field id parent-n own-index)))
    (lambda (r)
      (if (not (and (vector? r) (> (vector-length r) off)
                    (jolt-record-ancestor? (vector-ref r 0) id)))
          (error 'record-accessor "not an instance of this record type" id r))
      (vector-ref r off))))

(define (make-jolt-record-setter id parent-n own-index)
  (let ((off (make-jolt-record-field id parent-n own-index)))
    (lambda (r v)
      (if (not (and (vector? r) (> (vector-length r) off)
                    (jolt-record-ancestor? (vector-ref r 0) id)))
          (error 'record-setter "not an instance of this record type" id r))
      (vector-set! r off v))))

;; Build the record type and eval its ctor/pred/accessor/setter bindings into
;; the interaction environment (names computed from the record name exactly as
;; Chez generates them: make-<name>/<name>?/<name>-<field>/<name>-<field>-set!
;; for a bare name-spec, or the explicit ctor/pred from (name ctor pred)).
(define (make-jolt-record-type name ctor pred parent-name fields)
  (let* ((parent-id (and parent-name (jolt-record-id-of parent-name)))
         (parent-n (if parent-id (jolt-record-nfields parent-id) 0))
         (id (register-jolt-record-type! name parent-name fields))
         (env (interaction-environment))
         (nstr (symbol->string name))
         (ctor-name (or ctor (string->symbol (string-append "make-" nstr))))
         (pred-name (or pred (string->symbol (string-append nstr "?")))))
    (eval (list 'define ctor-name (list 'make-jolt-record-ctor id
                                        (+ parent-n (length fields))))
          env)
    (eval (list 'define pred-name (list 'make-jolt-record-pred id)) env)
    (let loop ((j 0) (fs fields))
      (if (pair? fs)
          (let* ((spec (car fs))               ; (kind . name) or (kind name acc [set])
                 (named? (pair? (cdr spec)))
                 (f (if named? (cadr spec) (cdr spec)))
                 (acc (if named?
                          (caddr spec)
                          (string->symbol (string-append nstr "-" (symbol->string f)))))
                 (setn (if (and named? (pair? (cdddr spec)))
                           (cadddr spec)
                           (string->symbol (string-append (symbol->string acc) "-set!")))))
            (eval (list 'define acc (list 'make-jolt-record-accessor
                                          id parent-n j))
                  env)
            ;; R6RS: only (mutable f) fields have a mutator binding.
            (when (eq? (car spec) 'mutable)
              (eval (list 'define setn (list 'make-jolt-record-setter
                                             id parent-n j))
                    env))
            (loop (+ j 1) (cdr fs)))
          #f))
    id))

;; R6RS record runtime introspection over the shim registry. CENSUS (boot
;; manifest, 2026-08-11): record-constructor + record-type-descriptor only, the
;; make-pmap/make-pset raw-constructor fast paths in collections.ss. Under the
;; shim a record type NAME is bound to its registered id (make-jolt-record-type
;; returns it), so the descriptor is the registry rtd and the raw constructor
;; is rebuilt from it.
(define (record-type-descriptor name)
  (if (fixnum? name) (table-ref jolt-record-id-table name #f) #f))
(define (record-constructor rtd)
  (if (vector? rtd)
      (let ((id (vector-ref rtd 0)) (n (vector-ref rtd 2)))
        (make-jolt-record-ctor id n))
      (error 'record-constructor "not a jolt record descriptor" rtd)))

;; field-spec extraction: (kind . name) pairs, or (kind name accessor [mutator])
;; when the spec names its accessor and mutator itself, as R6RS allows and
;; seq.ss uses. R6RS semantics: a PLAIN spec is IMMUTABLE — only (mutable f)
;; fields get a setter binding.
(define-syntax jolt-record-field-names
  (syntax-rules (mutable immutable)
    ((_ ()) '())
    ((_ ((mutable f acc set) rest ...)) (cons (list 'mutable 'f 'acc 'set) (jolt-record-field-names (rest ...))))
    ((_ ((immutable f acc) rest ...)) (cons (list 'immutable 'f 'acc) (jolt-record-field-names (rest ...))))
    ((_ ((mutable f) rest ...)) (cons (cons 'mutable 'f) (jolt-record-field-names (rest ...))))
    ((_ ((immutable f) rest ...)) (cons (cons 'immutable 'f) (jolt-record-field-names (rest ...))))
    ((_ (f rest ...)) (cons (cons 'immutable 'f) (jolt-record-field-names (rest ...))))))

(define-syntax define-record-type
  (syntax-rules (fields mutable immutable nongenerative parent protocol)
    ((_ (name ctor pred) (parent p) (fields spec ...) (nongenerative uid))
     (define name (make-jolt-record-type 'name 'ctor 'pred 'p
                                         (jolt-record-field-names (spec ...)))))
    ((_ (name ctor pred) (fields spec ...) (nongenerative uid))
     (define name (make-jolt-record-type 'name 'ctor 'pred #f
                                         (jolt-record-field-names (spec ...)))))
    ((_ (name ctor pred) (parent p) (fields spec ...))
     (define name (make-jolt-record-type 'name 'ctor 'pred 'p
                                         (jolt-record-field-names (spec ...)))))
    ((_ (name ctor pred) (fields spec ...))
     (define name (make-jolt-record-type 'name 'ctor 'pred #f
                                         (jolt-record-field-names (spec ...)))))
    ((_ name (fields spec ...) (nongenerative uid))
     (define name (make-jolt-record-type 'name #f #f #f
                                         (jolt-record-field-names (spec ...)))))
    ((_ name (fields spec ...))
     (define name (make-jolt-record-type 'name #f #f #f
                                         (jolt-record-field-names (spec ...)))))
    ((_ name (parent p) (fields spec ...) (nongenerative uid))
     (define name (make-jolt-record-type 'name #f #f 'p
                                         (jolt-record-field-names (spec ...)))))
    ((_ name (parent p) (fields spec ...))
     (define name (make-jolt-record-type 'name #f #f 'p
                                         (jolt-record-field-names (spec ...)))))
    ((_ (name ctor pred) (nongenerative uid))
     (define name (make-jolt-record-type 'name 'ctor 'pred #f '())))
    ((_ name (nongenerative uid))
     (define name (make-jolt-record-type 'name #f #f #f '())))
    ((_ name (protocol p) rest ...)
     (error 'define-record-type "protocol clauses are unsupported on the gambit target" 'name))))

;; ============================================================================
;; R6RS hashtable API over Gambit tables.
;;
;; CENSUS (curated subset, 2026-08-07): make-hashtable 53, hashtable-ref 170,
;; hashtable-set! 97, hashtable-keys 22, hashtable-delete! 17, make-weak-eq-
;; hashtable 10, make-eq-hashtable 6, hashtable-contains? 6, hashtable-values 5
;; (CONTRACT misc), hashtable-entries 4, hashtable-size 3, make-eqv-hashtable 1,
;; hashtable-cells 0 (CONTRACT misc). hashtable-update!/copy/mutable?/symbol-
;; hashtable? are NOT used in the subset — deliberately not shimmed.
;;
;; make-hashtable is always called with a hash function + equiv predicate
;; (e.g. (make-hashtable string-hash string=?)). Gambit tables hash internally
;; (equal?-consistent), so the hash argument is accepted and DROPPED — every
;; table operation is behaviorally identical; the hash function is only an
;; internal implementation detail. string-hash is provided so the argument
;; expression evaluates.
;; ============================================================================

(define (string-hash s) (equal?-hash s))

(define (make-eq-hashtable . rest) (make-table test: eq?))
(define (make-eqv-hashtable . rest) (make-table test: eqv?))
(define (make-weak-eq-hashtable) (make-table test: eq? weak-keys: #t))
(define (make-hashtable hash-fn equiv) (make-table test: equiv))

(define (hashtable-ref t k d) (table-ref t k d))
(define (hashtable-set! t k v) (table-set! t k v))
;; Gambit deletion is (table-set! t k) with no value (G0 probe: delete = set!
;; with no value; there is no table-delete!).
(define (hashtable-clear! t)
  (for-each (lambda (kv) (table-set! t (car kv))) (table->list t)))
(define (hashtable-delete! t k) (table-set! t k))
(define (hashtable-size t) (table-length t))

(define %hashtable-missing (gensym 'hashtable-missing))
(define (hashtable-contains? t k)
  (not (eq? (table-ref t k %hashtable-missing) %hashtable-missing)))

;; R6RS hashtable-keys returns a VECTOR.
(define (hashtable-keys t)
  (list->vector (map car (table->list t))))

;; R6RS hashtable-entries returns TWO values: keys vector, values vector.
(define (hashtable-entries t)
  (let ((cells (table->list t)))
    (values (list->vector (map car cells))
            (list->vector (map cdr cells)))))

;; CONTRACT misc: hashtable-values (vector of values), hashtable-cells (list of
;; (key . value) pairs).
(define (hashtable-values t)
  (list->vector (map cdr (table->list t))))

(define (hashtable-cells t)
  (table->list t))

;; R6RS (hashtable-copy t [mutable?]) over table-copy, which keeps the source's
;; test and weakness — records.ss copies the weak deftype-ctor-tag table on
;; every deftype and expects the copy to stay weak.
(define (hashtable-copy t . mutable?) (table-copy t))

;; ============================================================================
;; fx spelling aliases.
;;
;; CENSUS: fx+ 146, fx- 56, fx=? 55, fx<? 47, fx>? 31, fxand 26, fx* 10, fxsra 7,
;; fxsll 6, fxmax 5, fxior 5, fxnot 2, fxmin 2, fxremainder 1, fxquotient 1.
;; fl=? 1 (hasheq's -0.0 arm) -> Gambit fl=.
;; Gambit binds fx+ fx- fx* fxand fxior fxnot fxmax fxmin fxquotient fxremainder
;; natively; fx=?/fx<?/fx>? need the trailing-? spellings, and fxsll/fxsra map to
;; fxarithmetic-shift-left/right. fx<=? fx>=? fx1+ fx1- fxsrl: zero uses in the
;; subset — not aliased.
;; ============================================================================

;; JS-TARGET CONSTRAINT: Gambit-js fixnums are ~30-bit (tagged), so 32-bit
;; hash values overflow Gambit's NATIVE fx ops there ((fxarithmetic-shift-right
;; 704819571 0) is a FIXNUM-expected error under node while fine on gsi). The
;; aliases therefore map to GENERIC arithmetic — correct on both targets;
;; performance is not a goal on this target.
;; The NATIVE fx ops carry the same ~30-bit ceiling — host code runs 32-bit
;; hash intermediates through fx+/fx*/fxand (146/10/26 sites), so those shadow
;; to generic arithmetic too. Same correctness-over-speed call as the aliases.
(define (fx+ . xs) (apply + xs))
(define (fx- . xs) (apply - xs))
(define (fx* . xs) (apply * xs))
(define (fxand . xs) (apply bitwise-and xs))
(define (fxior . xs) (apply bitwise-ior xs))
(define (fxnot x) (bitwise-not x))
(define (fxmax . xs) (apply max xs))
(define (fxmin . xs) (apply min xs))
(define (fxquotient a b) (quotient a b))
(define (fxmodulo a b) (modulo a b))
(define (fxbit-count x) (bit-count x))
(define (fxxor . xs) (apply bitwise-xor xs))
(define (fxlogand . xs) (apply bitwise-and xs))
(define (fxlogor . xs) (apply bitwise-ior xs))
(define (fxlogxor . xs) (apply bitwise-xor xs))
(define (fxzero? x) (zero? x))
(define (fxsrl x n) (arithmetic-shift (bitwise-and x #xFFFFFFFFFFFFFFFF) (- n)))
(define (fxarithmetic-shift-right x n) (arithmetic-shift x (- n)))
(define (fxarithmetic-shift-left x n) (arithmetic-shift x n))
(define (fxremainder a b) (remainder a b))

(define-syntax fx=?
  (syntax-rules () ((_ a ...) (= a ...))))
(define-syntax fx<?
  (syntax-rules () ((_ a ...) (< a ...))))
(define-syntax fx>?
  (syntax-rules () ((_ a ...) (> a ...))))
(define-syntax fxsll
  (syntax-rules () ((_ a b) (arithmetic-shift a b))))
(define-syntax fxsra
  (syntax-rules () ((_ a b) (arithmetic-shift a (- b)))))

;; ../chez/collections.ss declares its HAMT bitmap operators through
;; define-width-op, the form host/chez/hasheq.ss uses to pick fx vs generic
;; arithmetic by the target's fixnum width. This target's own hash engine is
;; host/gambit/hasheq.ss, so the Chez definition never loads here — and the
;; question it answers is already settled above: the fx aliases in this file ARE
;; the generic operators, for the same ~30-bit-fixnum reason Chez's tpb32l needs
;; the narrow arm. So always take the wide arm; it is bignum-safe on this target.
(define-syntax define-width-op
  (syntax-rules ()
    ((_ name wide narrow)
     (define-syntax name
       (syntax-rules () ((_ a (... ...)) (wide a (... ...))))))))

;; Chez fxlogbit? (i fx): #t when bit i of fixnum fx is set. Gambit 4.9.7 has
;; no bit-test primitive (no bitwise-bit-set? / fixnum bit-test in any module);
;; decompose via fxand + shift. Used by seq.ss's jolt-invoke* arity pre-checks
;; and the procedure-arity-mask probes below.
(define (fxlogbit? i fx)
  (not (fx=? 0 (fxand fx (fxarithmetic-shift-left 1 i)))))

;; Chez procedure-arity-mask: bitmask of the arg counts a procedure accepts.
;; Gambit 4.9.7 has NO arity introspection at all (procedure-arity exists in no
;; module — grep of the installed library confirms). Return the all-bits mask so
;; jolt-invoke*'s (fxlogbit? n (procedure-arity-mask f)) pre-check always passes
;; and the call proceeds — Gambit's own runtime raises on a real arity mismatch.
;; The Chez build keeps precise masks; this is a port-of-convenience shim.
(define (procedure-arity-mask f) -1)

;; R6RS bitwise-bit-set? (n i): #t when bit i of n is set. Gambit 4.9.7 lacks
;; it (records-gambit.ss's satisfies? path is the one user in the subset).
;; Same fx decomposition as fxlogbit? — the only caller passes a fixnum mask.
(define (bitwise-bit-set? n i)
  (not (fx=? 0 (fxand n (fxarithmetic-shift-left 1 i)))))

;; R6RS bitwise shift spellings (natives-num.ss is the one user in the subset:
;; jolt-bit-shift-left/right, bit-mask, jolt-bit-test — 6 call sites) → Gambit's
;; arithmetic-shift. Gambit does not bind the R6RS bitwise-arithmetic-shift-*
;; names; arithmetic-shift with a NEGATIVE count is the arithmetic right shift
;; (floor semantics — identical to R6RS bitwise-arithmetic-shift-right).
(define-syntax bitwise-arithmetic-shift-left
  (syntax-rules () ((_ x n) (arithmetic-shift x n))))
(define-syntax bitwise-arithmetic-shift-right
  (syntax-rules () ((_ x n) (arithmetic-shift x (- n)))))

;; ============================================================================
;; Chez condition accessors over Gambit error objects.
;;
;; CENSUS: condition-message 7, condition? 7, message-condition? 2,
;; condition-irritants 1. Gambit's (error 'who "msg" irr...) folds exactly like
;; Chez: error-object-message -> "msg", error-object-irritants -> (irr...).
;; Non-error raised values: condition? -> #f, message/irritants -> #f / '().
;; ============================================================================

;; Chez's (error who "msg" irritant ...) keeps WHO out of the message and the
;; irritants. Gambit's native error is message-first (a symbol who would BECOME
;; the message and push "msg" into the irritants — probed 4.9.7), so the shim
;; re-shapes: message = the string, irritants = the rest, who dropped (Gambit
;; has no who slot; the host's five error sites read message + irritants only).
(define %gambit-error error)
(define (error who . rest)
  (if (and (pair? rest) (string? (car rest)))
      (apply %gambit-error (car rest) (cdr rest))
      (apply %gambit-error who rest)))

;; Chez syntax-case has with-syntax; Gambit's (gambit) module exposes
;; syntax-case but not with-syntax. rt.ss's jolt-foreign-proc-safe transformer
;; uses it (a macro definition, so it must expand in the boot unit). The
;; standard with-syntax reduction over syntax-case: bind pattern vars from a
;; list of expression values.
(define-syntax with-syntax
  (syntax-rules ()
    ((_ ((p e) ...) body ...)
     (syntax-case (list e ...) ()
       ((p ...) body ...)))))

;; error-object? covers only what `error` raised. Gambit's OWN runtime
;; exceptions — unbound variable, wrong argument count, wrong type — are
;; separate object types it answers #f for, and there is no umbrella predicate
;; (no `exception?`, no `##exception?` in 4.9.7). Treating them as non-conditions
;; makes every host-level failure opaque to the shared code: records-interop
;; classifies a raise by `condition?`, so a Gambit error fell through to the
;; class-model default and rendered as "#object[:object]" with no message.
;;
;; display-exception describes any exception Gambit knows ("Unbound variable: x",
;; "Wrong number of arguments passed to procedure"), and prints the distinctive
;; "This object was raised: <v>" for a plain value — so the description itself is
;; the test, and a new exception type in a future Gambit is covered without a
;; list to maintain.
(define (%gambit-exception-text x)
  (guard (e (#t #f))
    (let ((s (call-with-output-string (lambda (p) (display-exception x p)))))
      (and (string? s)
           (> (string-length s) 0)
           (not (string-prefix? "This object was raised:" s))
           (%trim-trailing-newline s)))))

(define (%trim-trailing-newline s)
  (let loop ((n (string-length s)))
    (cond ((= n 0) "")
          ((memv (string-ref s (- n 1)) '(#\newline #\return)) (loop (- n 1)))
          (else (substring s 0 n)))))

(define (condition? x)
  (or (error-object? x) (and (%gambit-exception-text x) #t)))
(define (message-condition? x) (condition? x))
(define (condition-message c)
  (cond ((error-object? c) (error-object-message c))
        ((%gambit-exception-text c))
        (else #f)))
(define (condition-irritants c)
  (if (error-object? c) (error-object-irritants c) '()))
;; The R6RS condition-type predicates records-dispatch.ss's message rendering
;; asks (condition->message-string): only an error object carries irritants,
;; and no Gambit exception has a who slot (the error shim above folds a Chez
;; `who` into the message text), so who-condition? is #f and condition-who is
;; never reached. display-condition is display-exception's job here.
(define (irritants-condition? c) (error-object? c))
(define (who-condition? c) #f)
(define (condition-who c) #f)
(define (display-condition c . port)
  (display-exception c (if (pair? port) (car port) (current-output-port))))

;; ============================================================================
;; thread-name mappings (G0 verdicts: the PIN holds — parameters fork-inherit
;; into SRFI-18 threads; mutexes are non-recursive; condvar wait shape differs
;; from Chez condition-wait and is mapped here).
;; ============================================================================

(define (mutex-acquire m . rest)
  (if (pair? rest) (mutex-lock! m (car rest)) (mutex-lock! m)))
(define (mutex-release m) (mutex-unlock! m))

;; jolt-with-mutex is Chez locks.ss's carrier-aware with-mutex. This host has
;; no fiber carriers, so it is lock/unlock — defined HERE because shared chez
;; files run it at boot (values.ss interns its first keyword under the
;; keyword-table lock) and records-gambit.ss uses it in dispatch paths.
;; REENTRANT, because Chez mutexes are recursive and SRFI-18's are not: code
;; that relocks a mutex it holds (the interner does, first thing at boot) is
;; correct on Chez and a self-deadlock here unless the held case runs inline.
(define (jwm-call mu thunk)
  (if (eq? (mutex-state mu) (current-thread))
      (thunk)
      (dynamic-wind (lambda () (mutex-lock! mu))
                    thunk
                    (lambda () (mutex-unlock! mu)))))
(define-syntax jolt-with-mutex
  (syntax-rules ()
    ((_ m e1 e2 ...) (jwm-call m (lambda () e1 e2 ...)))))

(define-syntax with-mutex
  (syntax-rules ()
    ((_ m e1 e2 ...) (jwm-call m (lambda () e1 e2 ...)))))

(define (make-thread-parameter init) (make-parameter init))

;; Chez's fences, which seq.ss and lazy-bridge.ss issue before publishing a
;; forced tail on the multi-threaded path. Gambit's Scheme-level threads are
;; green threads on one OS thread, so ordering across them is program order.
(define (memory-order-release) #!void)
(define (memory-order-acquire) #!void)

;; SRFI-18 spellings: make-condition-variable / condition-variable-signal! /
;; condition-variable-broadcast.
(define (make-condition) (make-condition-variable))
(define (condition-signal cv) (condition-variable-signal! cv))
(define (condition-broadcast cv) (condition-variable-broadcast! cv))

;; (condition-wait cv m [timeout]) — the SRFI-18 idiom is a single
;; (mutex-unlock! m cv [timeout]) call: it releases M, waits on CV (or times
;; out), and RE-ACQUIRES M before returning. Unit-tested in gambitcheck.
(define (condition-wait cv m . rest)
  ;; SRFI-18's (mutex-unlock! m cv [timeout]) releases M and waits, but does
  ;; NOT re-acquire on wake — Chez's condition-wait DOES, and every host wait
  ;; loop assumes it (unlock follows the loop). Re-lock before returning.
  ;; A NUMBER timeout is normalized to a time object: the js runtime treats a
  ;; raw absolute-seconds real as a setTimeout DELAY (32-bit-overflow warnings,
  ;; infinite reschedule loop — probed under node); a time object works on
  ;; both targets.
  (let ((r (if (pair? rest)
               (let ((t (car rest)))
                 (mutex-unlock! m cv (if (number? t) (seconds->time t) t)))
               (mutex-unlock! m cv))))
    (mutex-lock! m)
    r))

(define (fork-thread thunk) (thread-start! (make-thread thunk)))

;; CONTRACT: get-thread-id is a NUMBER, distinct per live thread. Gambit has no
;; native thread ids, so a weak table maps thread objects to a monotonic
;; counter. Weak keys so a dead thread's slot (and id) can be reclaimed.
(define thread-id-table (make-table test: eq? weak-keys: #t))
(define thread-id-mutex (make-mutex))
(define thread-id-counter 0)

(define (get-thread-id)
  (let ((t (current-thread)))
    (or (table-ref thread-id-table t #f)
        (begin
          (mutex-lock! thread-id-mutex)
          (let ((id (or (table-ref thread-id-table t #f)
                        (begin (set! thread-id-counter (+ thread-id-counter 1))
                               (table-set! thread-id-table t thread-id-counter)
                               thread-id-counter))))
            (mutex-unlock! thread-id-mutex)
            id)))))

;; ============================================================================
;; CONTRACT misc names (system/sort/time helpers the host spells differently).
;; ============================================================================

;; Chez sort shape is (sort predicate list); Gambit's native is list-sort with
;; the same (less? list) order.
(define (sort pred lst) (list-sort pred lst))

(define (list-head lst n)
  (let loop ((lst lst) (n n) (acc '()))
    (if (<= n 0)
        (reverse acc)
        (loop (cdr lst) (- n 1) (cons (car lst) acc)))))

;; iota / vector-copy / box / unbox / set-box! / void / gensym / pretty-print /
;; getenv / system come from (gambit) natively; format/printf/fprintf are shimmed below.

;; R6RS sleep takes a TIME object; Gambit's thread-sleep! takes real seconds.
(define (sleep t)
  (if (number? t)
      (thread-sleep! t)
      (thread-sleep! (time->seconds t))))

;; CONTRACT: current-time accepts the R6RS one-arg time-type form AND the Chez
;; zero-arg form. Gambit's native is zero-arg only; the type argument is ignored
;; (a utc time object is monotonic enough for elapsed deltas within a process).
(define %gambit-current-time current-time)
(define (current-time . rest) (%gambit-current-time))

;; make-time is not bound natively (and unused in the curated subset — the
;; CONTRACT comment mentions the host passing make-time results to sleep).
;; R6RS order: (make-time type nanosecond second).
(define (make-time type nanosecond second)
  (seconds->time (+ second (/ nanosecond 1000000000))))

;; CONTRACT misc: system is the shell-out; Gambit spells it shell-command.
(define (system cmd) (shell-command cmd))

;; CONTRACT: getenv — Chez's (getenv "NAME") returns #f when the variable is
;; unset; Gambit's raises ("Unbound OS environment variable"). Preserve the
;; zero-arg alist form and the optional-default form; make the bare string form
;; Chez-shaped.
(define %gambit-getenv getenv)
(define (getenv key . rest)
  (if (null? rest)
      (guard (e (#t #f)) (%gambit-getenv key))
      (apply %gambit-getenv key rest)))

;; CONTRACT: fork-thread — Chez's spawn; Gambit composes make-thread +
;; thread-start!. lazy-bridge.ss shadows it to flip jolt-mt? and track live
;; threads, so it must exist before that file loads.
(define (fork-thread thunk) (thread-start! (make-thread thunk)))

(define (scheme-version)
  (guard (e (#t "Gambit Scheme"))
    (##version-string)))

;; Chez's equal-hash. Gambit's equal?-hash exists in gsi but is NOT linked
;; into a gsc -target js exe (void at runtime — the let-values class, runtime
;; edition). Guarded: native when linked, else a portable object->string fold
;; (equal? values print identically for the key shapes the host hashes).
(define (%string-fold-hash s)
  (let ((n (string-length s)))
    (let loop ((i 0) (h 0))
      (if (>= i n) h
          (loop (+ i 1)
                (bitwise-and (+ (* h 31) (char->integer (string-ref s i)))
                             #x3FFFFFFF))))))
(define (equal-hash x)
  (guard (e (#t (%string-fold-hash (object->string x))))
    (equal?-hash x)))

;; CONTRACT: format is the ~a ~s ~d ~% ~~ subset (SRFI-28); printf/fprintf are
;; format to the current/given output port. Gambit binds NONE of these natively
;; (probed 4.9.7) — the earlier note claiming they come from (gambit) was wrong.
(define (%format-to port fmt args)
  (let ((n (string-length fmt)))
    (let loop ((i 0) (args args))
      (when (< i n)
        (let ((c (string-ref fmt i)))
          (if (and (char=? c #\~) (< (+ i 1) n))
              (let ((d (string-ref fmt (+ i 1))))
                (case d
                  ((#\a #\A) (display (car args) port) (loop (+ i 2) (cdr args)))
                  ((#\s #\S) (write (car args) port) (loop (+ i 2) (cdr args)))
                  ((#\d #\D) (display (car args) port) (loop (+ i 2) (cdr args)))
                  ((#\%) (newline port) (loop (+ i 2) args))
                  ((#\~) (display #\~ port) (loop (+ i 2) args))
                  (else (display c port) (loop (+ i 1) args))))
              (begin (display c port) (loop (+ i 1) args))))))))

;; R6RS fold-left / fold-right — Gambit binds neither (its SRFI-1 fold has a
;; DIFFERENT proc arg order: (kons x acc) vs R6RS's (f acc x)). Direct ports.
(define (fold-left f init . lists)
  (if (null? (cdr lists))
      (let loop ((acc init) (l (car lists)))
        (if (null? l) acc (loop (f acc (car l)) (cdr l))))
      (let loop ((acc init) (ls lists))
        (if (null? (car ls)) acc
            (loop (apply f acc (map car ls)) (map cdr ls))))))
(define (fold-right f init . lists)
  (if (null? (cdr lists))
      (let loop ((l (car lists)))
        (if (null? l) init (f (car l) (loop (cdr l)))))
      (let loop ((ls lists))
        (if (null? (car ls)) init
            (apply f (append (map car ls) (list (loop (map cdr ls)))))))))

;; R6RS (rnrs lists) for-all / exists — Gambit has SRFI-1's every / any under
;; different names and the same contract (the last application's value is the
;; result; the empty list answers #t / #f). seq.ss, vars.ss, dyn-binding.ss and
;; predicates.ss use them: (range 5) died on for-all and every gate was green.
(define (for-all pred . lists) (apply every pred lists))
(define (exists pred . lists) (apply any pred lists))

;; R6RS (remp pred list) / (remv obj list): SRFI-1's remove is the same as remp;
;; remv keeps the elements that are not eqv? to obj (atoms.ss's remove-watch,
;; regex-translate.ss).
(define (remp pred lst) (remove pred lst))
(define (remv obj lst) (remove (lambda (x) (eqv? x obj)) lst))

;; R6RS real->flonum: seq.ss's numeric macros widen an exact operand with it
;; before every mixed fl* / fl+, so (* 2 1.5) reached an unbound global.
(define (real->flonum x) (exact->inexact x))

;; Chez bignum?: an exact integer outside the fixnum range (natives-format.ss).
(define (bignum? x) (and (exact-integer? x) (not (fixnum? x))))

;; R6RS char-general-category backs the \p{L}-style classes in
;; regex-translate.ss. Gambit exposes no Unicode general categories, so such a
;; pattern is refused as a syntax error (regex.ss's guard turns this raise into
;; the PatternSyntaxException) rather than matched wrongly or left to die on an
;; unbound global.
(define (char-general-category c)
  (error 'char-general-category
         "\\p{...} character classes are unsupported on the gambit target"))

;; R6RS get-line / put-string over Gambit's read-line / write-string.
(define (get-line port) (read-line port))
(define (put-string port s) (write-string s port))

;; Chez's format accepts a #f port meaning "to a string" — records.ss calls
;; (format #f "f~a" i). The plain SRFI-28 spelling (format "~a" x) is the
;; default; a leading #f shifts to the next arg as the format string.
(define (format fmt . args)
  (if (eq? fmt #f)
      (call-with-output-string (lambda (p) (%format-to p (car args) (cdr args))))
      (call-with-output-string (lambda (p) (%format-to p fmt args)))))

(define (printf fmt . args)
  (%format-to (current-output-port) fmt args))

(define (fprintf port fmt . args)
  (%format-to port fmt args))

;; make-thread-parameter — Chez spelling; Gambit has no such name (probed
;; 4.9.7). Plain make-parameter IS thread-aware here (G0 pin: parameters
;; fork-inherit into SRFI-18 threads), which is the whole point of Chez's
;; thread parameters, so the alias is faithful. rt-core's throw-site params
;; (jolt-throw-cont/sitep) and print depth use it.
(define (make-thread-parameter v) (make-parameter v))

;; virtual-register / set-virtual-register!: Chez's fixed per-thread slot
;; array (rt-core claims slots 2/3/4; seq.ss's claim path counts into 7).
;; Gambit has no equivalent, so each thread carries its own vector of slots in
;; its thread-specific field, made on first touch. That gives Chez's two
;; properties: a slot is this thread's alone, and a FRESH THREAD STARTS EVERY
;; SLOT AT FIXNUM 0 -- nothing is inherited. A parameter per slot, which this
;; used to be, has neither: a parameter fork-inherits into a SRFI-18 thread
;; (the G0 pin, and the reason make-thread-parameter above is an alias), so a
;; child started with its parent's value, which is the one thing a per-thread
;; interrupt box or cache must never do. gambitcheck.ss pins the contract.
(define (%vreg-slots)
  (let* ((t (current-thread)) (v (thread-specific t)))
    (if (vector? v)
        v
        (let ((v (make-vector 16 0))) (thread-specific-set! t v) v))))
(define (virtual-register n) (vector-ref (%vreg-slots) n))
(define (set-virtual-register! n v) (vector-set! (%vreg-slots) n v))
(define (virtual-register-count) 16)

;; locks.ss's lock count, which seq.ss's force-claimed! keeps while a tail
;; thunk runs. On Chez the scheduler reads it to refuse preempting a fiber that
;; holds a lock; this host has no fibers, so the count is kept and nothing
;; consults it.
(define (jolt-locks-enter!) (set-virtual-register! 7 (+ 1 (virtual-register 7))))
(define (jolt-locks-exit!) (set-virtual-register! 7 (- (virtual-register 7) 1)))

;; locks.ss's explicit acquire/release pair, for the paths that hold a mutex
;; by hand across a dynamic-wind (regex.ss's pattern cache). Same shape as
;; Chez's: (jolt-lock! mu) blocks, (jolt-lock! mu #f) tries and answers #f, and
;; the lock count above moves with the mutex. Recursive like Chez's mutexes and
;; jwm-call above: a re-lock by the holder counts up instead of deadlocking on
;; SRFI-18's non-recursive mutex, and only the matching unlock releases it.
(define %jolt-lock-depth (make-table test: eq? weak-keys: #t))
(define jolt-lock!
  (case-lambda
    ((mu) (jolt-lock! mu #t))
    ((mu block?)
     (if (eq? (mutex-state mu) (current-thread))
         (begin (table-set! %jolt-lock-depth mu (+ 1 (table-ref %jolt-lock-depth mu 1)))
                (jolt-locks-enter!)
                #t)
         (let ((got (if block? (mutex-lock! mu) (mutex-lock! mu 0))))
           (when got (table-set! %jolt-lock-depth mu 1) (jolt-locks-enter!))
           got)))))
(define (jolt-unlock! mu)
  (let ((d (table-ref %jolt-lock-depth mu 1)))
    (if (> d 1)
        (table-set! %jolt-lock-depth mu (- d 1))
        (begin (table-set! %jolt-lock-depth mu) (mutex-unlock! mu)))
    (jolt-locks-exit!)))

;; str-trim — String.trim (java/natives-str.ss, which G2 excludes): chars at or
;; below space. rt-core.ss binds clojure.core/trim to it.
(define (str-trim s)
  (let ((len (string-length s)))
    (let scan-l ((i 0))
      (cond ((fx=? i len) "")
            ((char<=? (string-ref s i) #\space) (scan-l (fx+ i 1)))
            (else (let scan-r ((j (fx- len 1)))
                    (if (char<=? (string-ref s j) #\space)
                        (scan-r (fx- j 1))
                        (substring s i (fx+ j 1)))))))))

;; parse-int-or-throw — natives-misc.ss's jolt-bigint is the only caller here (G2
;; EXCLUDES the java/ tree, so none of the java.lang parsers exist on this host).
;; The GRAMMAR is not copied: java-int-parse is in natives-num.ss, which both
;; hosts include, so the one place jolt reads a Java integer cannot drift between
;; them. bigint is the unbounded parse, so there is no width to name and only the
;; ordinary "For input string:" message can come out.
(define (parse-int-or-throw s radix type)
  (let* ((str (if (string? s) s (jolt-str-render-one s)))
         (v (java-int-parse str radix #f #f)))
    (if (symbol? v)
        (jolt-throw (jolt-host-throwable "java.lang.NumberFormatException"
                      (string-append "For input string: \"" str "\"")))
        v)))

;; make-thread-parameter — a Chez PRIMITIVE (no .ss definition), absent on Gambit.
;; compile-eval.ss's jolt-current-source / jolt-aot-capture* are thread parameters;
;; a plain Gambit parameter covers the single-threaded boot (parameter/v protocol
;; matches: (p) get, (p v) set).
(define (make-thread-parameter v) (make-parameter v))

;; register-class-statics! — host-static.ss is in the G2-excluded java/ tree, but
;; compile-eval.ss registers the JVM-Compiler statics emulation (Compiler/LINE,
;; /COLUMN, /specials, /CHAR_MAP, /demunge) at its load time. Real minimal
;; registry with the same FQN+short-merge semantics as host-static.ss, so the
;; registration is recorded rather than dropped; nothing reads the table on the
;; gambit boot (no host interop) — this is a binding seam, not a feature.
(define class-statics-tbl (make-hashtable string-hash string=?))
(define (short-class-name s)
  (let loop ((i (- (string-length s) 1)))
    (cond ((< i 0) s)
          ((char=? (string-ref s i) #\.) (substring s (+ i 1) (string-length s)))
          (else (loop (- i 1))))))
(define (register-class-statics! name members)
  (let ((h (or (hashtable-ref class-statics-tbl name #f)
               (hashtable-ref class-statics-tbl (short-class-name name) #f)
               (make-hashtable string-hash string=?))))
    (hashtable-set! class-statics-tbl name h)
    (unless (string=? name (short-class-name name))
      (hashtable-set! class-statics-tbl (short-class-name name) h))
    (for-each (lambda (p) (hashtable-set! h (car p) (cdr p))) members)))
;; The two are one procedure here. On Chez they differ only in whether the class
;; is also recorded as one the RUNTIME provides (host-static.ss), and the gambit
;; boot has no provider registry to ask — records-dispatch.ss's defrecord
;; `create` takes the merge, so the name has to exist.
(define (class-statics-merge! name members) (register-class-statics! name members))

;; Chez gensym accepts a STRING prefix; Gambit only a symbol. Normalize.
(define %gambit-gensym gensym)
(define (gensym . p)
  (if (and (pair? p) (string? (car p)))
      (%gambit-gensym (string->symbol (car p)))
      (apply %gambit-gensym p)))

(define-syntax fl=?
  (syntax-rules () ((_ a ...) (fl= a ...))))
(define-syntax fx<=?
  (syntax-rules () ((_ a ...) (<= a ...))))
(define-syntax fx>=?
  (syntax-rules () ((_ a ...) (>= a ...))))
(define-syntax fx1+
  (syntax-rules () ((_ a) (+ a 1))))
(define-syntax fx1-
  (syntax-rules () ((_ a) (- a 1))))
