;; unbound-check.ss — every Scheme global the Gambit boot references is defined.
;;
;; The boot ##include-splices most of host/chez, and a Chez-side name that
;; reaches a shared file is an UNBOUND GLOBAL on Gambit: nothing fails at load,
;; the first call raises "Unbound variable: x" with no jolt context, and — the
;; part this gate exists for — nothing in the Chez suite can see it. mirrordrift
;; compares procedures defined in BOTH rt.ss and rt-core.ss, so a NEW name (a
;; parameter host-contract.ss started reading, an R6RS list op a shared file
;; picked up) is invisible to it. `make gambiteval` had every row failing for
;; two weeks that way (jolt-cw2p).
;;
;; The oracle is Gambit's own linker: `gsc -warnings -link` reports every global
;; referenced by the compiled unit and defined nowhere, after full macro
;; expansion — exact, with no free-variable analysis of our own to get wrong.
;; unbound-check.sh runs the compile and link and hands this script the link
;; log. Two things the linker cannot know are folded in here:
;;
;;   - a record's constructor/predicate/accessors come from the shim's
;;     define-record-type translator (prelude-shims.ss), which EVALS them into
;;     the interaction environment at boot, so the compiler never sees a
;;     define for them. Derived here from every define-record-type form in the
;;     booted manifest, by the translator's own naming rule.
;;   - an uninterned #:gN name is never a missing definition. It is the mark of
;;     Gambit's case-lambda expander dropping the rest parameter of a two-clause
;;     (fixed n / variadic n) fn (backend_scheme.clj emit-fn has the story), and
;;     it always fails: the fix is the emitter's merge, never an allowlist line.
;;
;; What is left is compared against host/gambit/unbound-allowlist.txt: names
;; referenced from paths this target never takes (the excluded java/ tree's
;; helpers behind capability checks, gsi runtime internals the js link file
;; does not carry). Like the portability allowlist, the list only shrinks
;; truthfully — a line whose name is now defined is STALE and fails the gate.
;;
;; Modes:
;;   <link-log>            gate — exit 1 on an unallowlisted name, a stale line,
;;                         or a #:gN name
;;   <link-log> --regen    rewrite the allowlist: comments and still-valid lines
;;                         kept in place, stale lines dropped, new names appended
;;   <link-log> --list     print every unbound name and how it was classified
(import (chezscheme))
(include "host/chez/gate-scan-lib.ss")

(define allowlist-path "host/gambit/unbound-allowlist.txt")
(define boot-path "host/gambit/boot-full.ss")

;; ---- the linker's report ----------------------------------------------------
;; Two lines per warning:
;;   *** WARNING -- "NAME" is not defined,
;;   ***            referenced in: ("FILE" ...)
;; A reference from the Gambit runtime library itself (_gambit.js names a few of
;; its own internals the js link file does not carry) is Gambit's business, not
;; the boot's: only a reference from the compiled boot counts.
(define (quoted-strings line)
  (let ((n (string-length line)))
    (let loop ((i 0) (acc '()))
      (cond ((>= i n) (reverse acc))
            ((char=? (string-ref line i) #\")
             (let scan ((j (+ i 1)))
               (cond ((>= j n) (reverse acc))
                     ((char=? (string-ref line j) #\")
                      (loop (+ j 1) (cons (substring line (+ i 1) j) acc)))
                     (else (scan (+ j 1))))))
            (else (loop (+ i 1) acc))))))

(define (runtime-library? path)
  (gs-string-suffix? "/_gambit.js" path))

(define (parse-link-log path)
  (let ((lines (call-with-input-file path
                 (lambda (p)
                   (let loop ((acc '()))
                     (let ((l (get-line p)))
                       (if (eof-object? l) (reverse acc) (loop (cons l acc)))))))))
    (let loop ((ls lines) (acc '()))
      (cond
        ((null? ls) (reverse acc))
        ((and (gs-string-prefix? "*** WARNING -- " (car ls))
              (gs-string-contains? (car ls) "is not defined")
              (pair? (cdr ls))
              (gs-string-contains? (cadr ls) "referenced in:"))
         (let ((name (car (quoted-strings (car ls))))
               (files (quoted-strings (cadr ls))))
           (loop (cddr ls)
                 (if (exists (lambda (f) (not (runtime-library? f))) files)
                     (cons name acc)
                     acc))))
        (else (loop (cdr ls) acc))))))

;; ---- the booted manifest ------------------------------------------------------
;; boot-full.ss (generated by gen-boot.ss) ##includes every file of the boot,
;; some of which ##include further (repl-main's boot-active, records-gambit's
;; none). Followed here relative to the including file, like Gambit does.
(define (includes-of path)
  (let loop ((fs (gs-read-forms path)) (acc '()))
    (if (null? fs)
        (reverse acc)
        (let ((d (car fs)))
          (loop (cdr fs)
                (if (and (pair? d) (eq? (car d) 'gambit-ns:include)
                         (pair? (cdr d)) (string? (cadr d)))
                    (cons (cadr d) acc)
                    acc))))))

(define (resolve-include from rel)
  (let ((dir (path-parent from)))
    (if (string=? dir "") rel (string-append dir "/" rel))))

(define (manifest root)
  (let walk ((p root))
    (cons p (apply append (map (lambda (r) (walk (resolve-include p r))) (includes-of p))))))

;; ---- names the record translator evals at boot --------------------------------
;; make-jolt-record-type (prelude-shims.ss): make-<name> / <name>? unless the
;; spec names them, <name>-<field> unless the field spec names its accessor, and
;; a -set! mutator (named or derived) for a MUTABLE field only. The translator's
;; own define-syntax is skipped: a template is not a definition.
(define (record-names d)
  (let* ((spec (cadr d))
         (name (if (pair? spec) (car spec) spec))
         (nstr (symbol->string name))
         (ctor (if (pair? spec) (cadr spec) (string->symbol (string-append "make-" nstr))))
         (pred (if (pair? spec) (caddr spec) (string->symbol (string-append nstr "?"))))
         (fields (let ((c (assq 'fields (cddr d)))) (if c (cdr c) '()))))
    (cons ctor
          (cons pred
                (apply append
                       (map (lambda (fs)
                              (let* ((kind (if (pair? fs) (car fs) 'immutable))
                                     (f (if (pair? fs) (cadr fs) fs))
                                     (acc (if (and (pair? fs) (pair? (cddr fs)))
                                              (caddr fs)
                                              (string->symbol (string-append nstr "-" (symbol->string f)))))
                                     (setter (if (and (pair? fs) (pair? (cddr fs)) (pair? (cdddr fs)))
                                                 (cadddr fs)
                                                 (string->symbol (string-append (symbol->string acc) "-set!")))))
                                (if (eq? kind 'mutable) (list acc setter) (list acc))))
                            fields))))))

(define (record-generated-names files)
  (let ((h (make-hashtable string-hash string=?)))
    (define (walk d)
      (when (pair? d)
        (cond
          ((eq? (car d) 'define-syntax) #f)
          ((and (eq? (car d) 'define-record-type) (pair? (cdr d)))
           (for-each (lambda (s) (hashtable-set! h (symbol->string s) #t)) (record-names d)))
          (else (let loop ((x d))
                  (when (pair? x) (walk (car x)) (loop (cdr x))))))))
    (for-each (lambda (f) (for-each walk (gs-read-forms f))) files)
    h))

;; ---- the allowlist --------------------------------------------------------------
;; One name per line; a line starting with # is a comment and is kept where it
;; is by --regen, so the classification a reader needs stays next to its names.
(define (read-allowlist-lines)
  (if (file-exists? allowlist-path)
      (call-with-input-file allowlist-path
        (lambda (p)
          (let loop ((acc '()))
            (let ((l (get-line p)))
              (if (eof-object? l) (reverse acc) (loop (cons l acc)))))))
      '()))

(define (comment-line? l)
  ;; "#" alone or "# text" — a name may start with ## (Gambit's own primitives)
  (or (string=? l "")
      (and (char=? (string-ref l 0) #\#)
           (or (= (string-length l) 1) (char=? (string-ref l 1) #\space)))))

(define (line-name l)
  ;; the first whitespace-delimited token
  (let loop ((i 0))
    (if (or (= i (string-length l)) (memv (string-ref l i) '(#\space #\tab)))
        (substring l 0 i)
        (loop (+ i 1)))))

(define (allowed-names lines)
  (map line-name (filter (lambda (l) (not (comment-line? l))) lines)))

(define header
  '("# unbound-allowlist.txt — Scheme globals the Gambit boot references and DOES NOT"
    "# define, each on a path this target never takes."
    "#"
    "# One name per line, grouped under a comment that says why the group is"
    "# unreachable here. host/gambit/unbound-check.ss (make gambitunbound) pins"
    "# this against Gambit's own linker report over the full-profile boot: a name"
    "# missing from this list fails the gate, and so does a line whose name has"
    "# since been defined — the list only shrinks truthfully. `make"
    "# gambitunbound-regen` keeps the comments and still-valid lines in place,"
    "# drops stale lines and appends new names at the end for classification."
    "#"
    "# A name here is a documented gap, not a free pass: reaching it raises"
    "# \"Unbound variable\" with no jolt context. Binding it — a mirror in"
    "# rt-core.ss, a shim in prelude-shims.ss, a raise naming the absent"
    "# capability — is always better than a line here."))

(define (write-allowlist! lines unbound)
  (let* ((kept (filter (lambda (l) (or (comment-line? l) (member (line-name l) unbound)))
                       lines))
         (have (allowed-names kept))
         (new (filter (lambda (n) (not (member n have))) unbound)))
    (call-with-output-file allowlist-path
      (lambda (p)
        (if (null? lines)
            (for-each (lambda (l) (display l p) (newline p)) header)
            (for-each (lambda (l) (display l p) (newline p)) kept))
        (when (pair? new)
          (display "#\n# NEW since the last regen — classify each under a group above, or bind it.\n" p)
          (for-each (lambda (n) (display n p) (newline p)) new)))
      'truncate)
    (values (length kept) (length new))))

;; ---- main ------------------------------------------------------------------------
(define (gensym-name? n)
  (and (> (string-length n) 1)
       (char=? (string-ref n 0) #\g)
       (let loop ((i 1))
         (or (= i (string-length n))
             (and (char-numeric? (string-ref n i)) (loop (+ i 1)))))))

(define (main args)
  (when (or (null? args) (gs-string-prefix? "--" (car args)))
    (printf "usage: unbound-check.ss <gsc-link-log> [--regen|--list]\n")
    (exit 2))
  (let* ((log-path (car args))
         (flags (cdr args))
         (reported (parse-link-log log-path))
         (files (manifest boot-path))
         (records (record-generated-names files))
         (unbound (list-sort string<?
                    (filter (lambda (n) (not (hashtable-ref records n #f))) reported)))
         (gensyms (filter gensym-name? unbound))
         (unbound (filter (lambda (n) (not (gensym-name? n))) unbound))
         (lines (read-allowlist-lines))
         (allow (allowed-names lines))
         (unallowed (filter (lambda (n) (not (member n allow))) unbound))
         (stale (filter (lambda (n) (not (member n unbound))) allow)))
    (printf "gambit unbound: ~a name(s) reported by the linker, ~a record-generated, ~a unbound\n"
            (length reported) (- (length reported) (length unbound) (length gensyms)) (length unbound))
    (cond
      ((member "--list" flags)
       (for-each (lambda (n)
                   (printf "  ~a~a\n" n (if (member n allow) "  (allowlisted)" "")))
                 unbound)
       (for-each (lambda (n) (printf "  ~a  (uninterned: case-lambda expansion)\n" n)) gensyms)
       (exit 0))
      ((member "--regen" flags)
       (let-values (((kept new) (write-allowlist! lines unbound)))
         (printf "gambit unbound: wrote ~a (~a line(s) kept, ~a new)\n" allowlist-path kept new))
       (when (pair? gensyms)
         (printf "\nNOT allowlisted — uninterned names from a case-lambda Gambit miscompiles:\n")
         (for-each (lambda (n) (printf "  ~a\n" n)) gensyms)
         (exit 1))
       (exit 0))
      (else
       (when (pair? unallowed)
         (printf "\nUNBOUND — referenced by the boot, defined nowhere, and not allowlisted:\n")
         (for-each (lambda (n) (printf "  ~a\n" n)) unallowed)
         (printf "\nBind each one (a mirror in host/gambit/rt-core.ss, a shim in prelude-shims.ss,\n")
         (printf "a named raise in host-vars.ss), or record a genuinely untaken path with\n")
         (printf "`make gambitunbound-regen` and classify it in ~a.\n" allowlist-path))
       (when (pair? stale)
         (printf "\nSTALE allowlist lines — these names are defined now. Drop them with\n")
         (printf "`make gambitunbound-regen`:\n")
         (for-each (lambda (n) (printf "  ~a\n" n)) stale))
       (when (pair? gensyms)
         (printf "\nUNINTERNED — a two-clause case-lambda (fixed n / variadic n) somewhere in the\n")
         (printf "boot: Gambit's expander drops its rest parameter (see emit-fn in\n")
         (printf "jolt-core/jolt/backend_scheme.clj). Emitted code takes the merged shape;\n")
         (printf "a hand-written one needs a third clause or a rest lambda:\n")
         (for-each (lambda (n) (printf "  ~a\n" n)) gensyms))
       (if (or (pair? unallowed) (pair? stale) (pair? gensyms))
           (exit 1)
           (begin (printf "gambit unbound: passed (~a allowlisted)\n" (length allow))
                  (exit 0)))))))

(main (cdr (command-line)))
