;; gen-core-docs.clj — regenerate jolt-core/clojure/core/90-docs.clj.
;;
;; Run on JVM Clojure (tools/gen-core-docs.sh). Reads a jolt var inventory
;; (ns-name -> [var-name ...], produced by the running jolt binary), looks each
;; var up in this JVM's clojure, and emits one attach form per var that has a
;; :doc or :arglists to contribute. Only vars jolt actually interns are emitted,
;; so jolt-internal names never mask and removed vars fall out on regeneration.
;;
;; args: <jolt-vars.edn> <out-file>
(require 'clojure.string 'clojure.walk 'clojure.template 'clojure.edn
         'clojure.set 'clojure.pprint 'clojure.repl)

(let [[inv-path out-path] *command-line-args*
      inventory (clojure.edn/read-string (slurp inv-path))
      header (str
              ";; clojure.core overlay shard — reference :doc/:arglists/:tag for the image-baked\n"
              ";; namespaces. GENERATED by tools/gen-core-docs.sh — do not edit by hand.\n"
              ";;\n"
              ";; Docstrings and arglists are from Clojure " (clojure-version)
              " (EPL-1.0,\n"
              ";; (c) Rich Hickey and contributors — https://github.com/clojure/clojure).\n"
              ";;\n"
              ";; Loaded LAST in the prelude (after every tier and image stdlib ns), so a\n"
              ";; :doc or :arglists the jolt source itself declares always wins — this file\n"
              ";; only fills what the source did not carry: native primitives (map/reduce/+\n"
              ";; are def-var!'d in Scheme with no meta) and ported sources whose docstrings\n"
              ";; were dropped. Lookup goes through jolt.host/find-var, NOT clojure.core\n"
              ";; find-var/resolve, so a tree-shaken build neither bails nor roots the\n"
              ";; documented vars; a var absent at runtime is silently skipped.\n"
              "\n"
              ";; :tag is the reference's own: a Class where the reference wrote the tag in a\n"
              ";; metadata map ((defn not {:tag Boolean} ...) evaluates it), a symbol where it\n"
              ";; wrote a ^Hint.\n"
              "\n"
              "(defn- attach-core-doc-meta!\n"
              "  [ns-name var-name doc args tag]\n"
              "  (when-let [v (jolt.host/find-var ns-name var-name)]\n"
              "    (alter-meta! v\n"
              "      (fn [m]\n"
              "        (let [m (if (and doc (nil? (get m :doc))) (assoc m :doc doc) m)\n"
              "              m (if (and tag (nil? (get m :tag))) (assoc m :tag tag) m)]\n"
              "          (if (and args (nil? (get m :arglists))) (assoc m :arglists args) m))))))\n")
      forms (for [[nsn var-names] (sort-by key inventory)
                  :let [ns-sym (symbol nsn)]
                  var-name var-names
                  :let [v (ns-resolve ns-sym (symbol var-name))
                        m (when (var? v) (meta v))
                        ;; only vars this JVM ns itself interns (ns-resolve also
                        ;; answers refers; a refer would attach the wrong home)
                        m (when (and m (= (str (:ns m)) nsn)) m)]
                  :when (or (:doc m) (:arglists m) (:tag m))]
              (str "(attach-core-doc-meta! " (pr-str nsn) " " (pr-str var-name)
                   "\n  " (pr-str (:doc m))
                   "\n  " (if (:arglists m) (str "'" (pr-str (:arglists m))) "nil")
                   "\n  " (let [t (:tag m)]
                            (cond (class? t) (str "(jolt.host/jolt-class-for " (pr-str (.getName ^Class t)) ")")
                                  (symbol? t) (str "'" (pr-str t))
                                  :else "nil"))
                   ")"))]
  (spit out-path (str header "\n" (clojure.string/join "\n" forms) "\n"))
  (println "wrote" out-path "-" (count forms) "vars"))
